# Generated by Django 5.2.17 on 2026-09-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(max_length=20, verbose_name="Tipo de documento"),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Número de documento"
                    ),
                ),
                ("nombres", models.CharField(max_length=100, verbose_name="Nombres")),
                (
                    "apellidos",
                    models.CharField(max_length=100, verbose_name="Apellidos"),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Femenino"),
                            ("O", "Otro"),
                            ("NR", "No registrado"),
                        ],
                        default="NR",
                        max_length=2,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Teléfono"
                    ),
                ),
                (
                    "correo_electronico",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "departamento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Departamento"
                    ),
                ),
                (
                    "municipio",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Municipio"
                    ),
                ),
                (
                    "tipo_trastorno",
                    models.CharField(
                        choices=[
                            ("HEMO_A", "Hemofilia A"),
                            ("HEMO_B", "Hemofilia B"),
                            ("VWD", "Enfermedad de Von Willebrand"),
                            ("OTRO", "Otro trastorno hemorrágico"),
                            ("PEND", "Pendiente de clasificación"),
                        ],
                        default="PEND",
                        max_length=20,
                        verbose_name="Tipo de trastorno hemorrágico",
                    ),
                ),
                (
                    "gravedad",
                    models.CharField(
                        choices=[
                            ("LEVE", "Leve"),
                            ("MOD", "Moderada"),
                            ("SEV", "Severa"),
                            ("NA", "No aplica"),
                            ("ND", "No determinada"),
                        ],
                        default="ND",
                        max_length=5,
                        verbose_name="Gravedad",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "ordering": ["apellidos", "nombres"],
            },
        ),
    ]
