# Generated by Django 5.2.17 on 2026-09-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registroauditoria",
            options={
                "ordering": ["-fecha_hora"],
                "permissions": [
                    (
                        "consultar_auditoria",
                        "Puede consultar los registros de auditoría",
                    )
                ],
                "verbose_name": "Registro de auditoría",
                "verbose_name_plural": "Registros de auditoría",
            },
        ),
    ]
